{% set version = "5.3" %}
{% set sha256 = "8a9fc92a83993de4f7a7d5900f2937b5dc3d167c8969a022bfdf7e58e7ff3f1c" %}

package:
  name: cat
  version: {{ version }}

source:
  url: https://github.com/dutilh/CAT/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }} 

build:
  number: 1
  noarch: generic
  run_exports:
    - {{ pin_subpackage("cat", max_pin="x") }}
requirements:
  run:
    - python 3
    - diamond
    - prodigal

test:
  commands:
    - CAT prepare --help

about:
  summary: |
    CAT/BAT: tool for taxonomic classification of contigs and metagenome-assembled genomes (MAGs)
  home: https://github.com/dutilh/CAT
  license: MIT
  license_file: LICENSE.md
