{% set version = "1.2.1" %}

package:
  name: assemblytics
  version: {{ version }}

source:
  url: https://github.com/MariaNattestad/Assemblytics/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2c2e40fca046a8be2714d2d570cd8aa96bfd1b92e214197ba6141de9f21a9edc
  patches:
    - libexec.patch

build:
  noarch: generic
  number: 2

requirements:
  run:
    - python
    - numpy
    - r-base
    - r-ggplot2
    - r-plyr
    - r-scales
    - r-rcolorbrewer
    - mummer

test:
  requires:
    - wget
    - unzip
  commands:
    - wget http://assemblytics.com/user_data/ecoli/E__coli_example.Assemblytics_results.zip
    - unzip E__coli_example.Assemblytics_results.zip
    - Assemblytics user_data/*/E__coli_example.Assemblytics.unique_length_filtered_l1000.delta.gz sample 10000 50 10000
    - rm -rf user_data sample* E__coli_example.Assemblytics_results.zip

about:
  home: http://assemblytics.com/
  license: MIT
  license_file: LICENSE
  summary: 'analyze a genome assembly by comparing it to a reference genome'
  description: >
    Assemblytics detects and analyzes variants from a de novo genome assembly aligned to a reference genome.
    It incorporates a unique anchor filtering approach to increase robustness to repetitive elements and identifies six classes of variants based on their distinct alignment signatures.
    Assemblytics can be applied both to comparing aberrant genomes, such as human cancers, to a reference, or to identify differences between related species.
