{% set version = "1.44.0" %}
{% set name = "EBcoexpress" %}
{% set bioc = "3.17" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a279447b6ebe095682a46c302d2759f3
build:
  number: 0
  run_exports: # run_exports这个要配置上, 不然提交可能check不通过
    - {{ pin_subpackage('bioconductor-ebcoexpress', max_pin="x.x") }}
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: graph, igraph, colorspace
requirements:
  host:
    - 'bioconductor-ebarrays >=2.64.0,<2.65.0'
    - r-base
    - r-mclust
    - r-minqa
    - libblas
    - liblapack
  run:
    - 'bioconductor-ebarrays >=2.64.0,<2.65.0'
    - r-base
    - r-mclust
    - r-minqa
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'EBcoexpress for Differential Co-Expression Analysis'
  description: 'An Empirical Bayesian Approach to Differential Co-Expression Analysis at the Gene-Pair Level'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra: # 一般我们要加这个extra配置,指示aarch64架构也支持,但是如果在build下已经指示是noarch了,就不要加这个了
  additional-platforms:
    - linux-aarch64
