{% set version = "1.62.1" %}
{% set name = "GeneticsPed" %}
{% set bioc = "3.17" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 49e37937196a5ec28dafaa5f2c6c0dda
build:
  number: 0
  run_exports: # run_exports这个要配置上, 不然提交可能check不通过
    - {{ pin_subpackage('bioconductor-geneticsped', max_pin="x.x") }}
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: RUnit, gtools
requirements:
  host:
    - r-base
    - r-gdata
    - r-genetics
    - r-mass
    - libblas
    - liblapack
  run:
    - r-base
    - r-gdata
    - r-genetics
    - r-mass
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2.1) | file LICENSE'
  summary: 'Pedigree and genetic relationship functions'
  description: 'Classes and methods for handling pedigree data. It also includes functions to calculate genetic relationship measures as relationship and inbreeding coefficients and other utilities. Note that package is not yet stable. Use it with care!'
  license_file: LICENSE
extra: # 一般我们要加这个extra配置,指示aarch64架构也支持,但是如果在build下已经指示是noarch了,就不要加这个了
  additional-platforms:
    - linux-aarch64

