package:
  name: apoc
  version: 1b16

source:
  url: http://cssb.biology.gatech.edu/skolnick/files/APoc/apoc_v1b16.tar.gz
  sha256: e66f33312e8a10b82ddc25a6ecdb1d178d9349a10e9be20d33b41ef75556dd51
  patches:
    - apoc_gfortran.patch

build:
  number: 6
  run_exports:
    - {{ pin_subpackage("apoc", max_pin="x.x.x") }}  

requirements:
  host:
    - make
    - {{ compiler('c') }} <=9.3.0
    - {{ compiler('fortran') }} <=9.3.0
  build:
    - make
    - {{ compiler('c') }} <=9.3.0
    - {{ compiler('fortran') }} <=9.3.0
  run:

test:
  commands:
    - apoc -h >/dev/null

about:
  home: http://cssb.biology.gatech.edu/APoc
  license: "This software is freely available to ALL users."
  summary: Large-scale structural comparison of protein pockets

extra:
  additional-platforms:
    - linux-aarch64
