{% set version = "1.52.0" %}
{% set name = "genoCN" %}
{% set bioc = "3.17" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 8b42af5b706f84966e90e5bc11fd129f
build:
  number: 0
  run_exports: # run_exports这个要配置上, 不然提交可能check不通过
    - {{ pin_subpackage('bioconductor-genocn', max_pin="x.x") }}
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'genotyping and copy number study tools'
  description: 'Simultaneous identification of copy number states and genotype calls for regions of either copy number variations or copy number aberrations'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra: # 一般我们要加这个extra配置,指示aarch64架构也支持,但是如果在build下已经指示是noarch了,就不要加这个了
  additional-platforms:
    - linux-aarch64
