{% set name = "bcbio-gff" %}
{% set version = "0.6.4" %}
{% set sha256 = "e0efddc2376ed11b8f9682029b58bfd523a9aa62199f870b4ce64509ff99820b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("bcbio-gff", max_pin="x.x.x") }}  
  noarch: python
  script: 
    #Starting from Biopython version 1.79, the UnknownSeq class has been moved . This change was made to better organize the codebase and improve clarity. Therefore, if you're using a newer version of Biopython (1.79 or later), you should from Bio.Seq import Seq  instead of UnknownSeq.
    - sed -i "32s/UnknownSeq/Seq/g" ./BCBio/GFF/GFFParser.py
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  
requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - biopython
    - bx-python

test:
  imports:
    - BCBio.GFF

about:
  home: https://github.com/chapmanb/bcbb/tree/master/gff
  license: Biopython License Agreement
  summary: A python library to read and write Generic Feature Format (GFF).
