{% set name = "MrBayes" %}
{% set version = "3.2.7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/NBISweden/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 64da39c01f606d0413ce90a1dd3c1ce2cbdef4cbad99aee8a4b2391a2e8db244

build:
  number: 7
  run_exports:
    - {{ pin_subpackage("mrbayes", max_pin="x.x.x") }}  

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - readline
    - openmpi
    {% if target_platform == "linux-aarch64" %}
    - beagle-lib
    {% else %}
    - beagle-lib <4
    {% endif %}
    - ncurses
  run:
    - readline
    - openmpi
    {% if target_platform == "linux-aarch64" %}
    - beagle-lib
    {% else %}
    - beagle-lib <4
    {% endif %}
    - ncurses

test:
# conda inspect rules broken in bioconda toolchain
#  requirements:
#    - conda
  commands:
#    - conda inspect linkages -p $PREFIX $PKG_NAME  # [linux]
#    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  - echo Version | mb
  - echo Version | mpirun -mca plm_rsh_agent true --allow-run-as-root mb-mpi

about:
  home: http://mrbayes.sourceforge.net
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: Bayesian Inference of Phylogeny
  description: |
    MrBayes is a program for Bayesian inference and model choice across a wide
    range of phylogenetic and evolutionary models. MrBayes uses Markov chain
    Monte Carlo (MCMC) methods to estimate the posterior distribution of model
    parameters.

extra:
  identifiers:
    - biotools:mrbayes
  additional-platforms:
    - linux-aarch64
