# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /opt/recipe, last modified Thu Feb 24 18:57:07 2022
# ------------------------------------------------

package:
  name: cpat
  version: 3.0.4
source:
  sha256: 6d832f20729f8fc814384a27a4fcebcf81b11c0e6d80a404b4c4860d17e7d935
  url: https://pypi.io/packages/source/C/CPAT/CPAT-3.0.4.tar.gz
build:
  number: '1'
  script: $PREFIX/bin/python
    -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .
  string: py39h5371cbf_1_kp
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-aarch64 2.36.1 h026399b_2
    - binutils_linux-aarch64 2.36 h7854541_10
    - gcc_impl_linux-aarch64 10.3.0 ha07e0e6_16
    - gcc_linux-aarch64 10.3.0 h4e3e293_10
    - kernel-headers_linux-aarch64
    - ld_impl_linux-aarch64 2.36.1 h02ad14f_2
    - libgcc-devel_linux-aarch64 10.3.0 h8e480ec_16
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libsanitizer 10.3.0 h971684a_16
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-aarch64
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 2_gnu
    - bx-python 0.8.13 py39h6471ffd_1_kp
    - bzip2 1.0.8 hfd63f10_2
    - c-ares 1.18.1 h2f4d8fa_0
    - ca-certificates 2021.10.8 h4fd8a4c_0
    - cython 0.29.28 py39h2f4d8fa_0
    - krb5 1.19.2 h7c456eb_4
    - ld_impl_linux-aarch64 2.36.1 h02ad14f_2
    - libblas 3.9.0 13_linuxaarch64_openblas
    - libcblas 3.9.0 13_linuxaarch64_openblas
    - libcurl 7.81.0 hcafe9da_0
    - libdeflate 1.10 hf897c2e_0
    - libedit 3.1.20191231 hfd63f10_0
    - libev 4.33 hfd63f10_1
    - libffi 3.4.2 h419075a_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgfortran-ng 11.2.0 h6e398d7_1
    - libgfortran5 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - liblapack 3.9.0 13_linuxaarch64_openblas
    - libnghttp2 1.47.0 h75cb1c7_0
    - libnsl 2.0.0 h998d150_0
    - libopenblas 0.3.18 hac96964_0
    - libssh2 1.10.0 h1ab2c7b_2
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 2.32.1 hf897c2e_1000
    - libzlib 1.2.11 h4e544f5_1014
    - lzo 2.10 hfd63f10_4
    - ncurses 6.3 h998d150_3
    - nose 1.3.7 pyhd3eb1b0_1008
    - numpy 1.19.5 py39h53e47e4_3
    - openssl 1.1.1l h2f4d8fa_0
    - pip 22.0.3 pyhd8ed1ab_0
    - pysam 0.18.0 py39h5030a8b_2_kp
    - python 3.9.10 he7f7bba_2_cpython
    - python-lzo 1.14 py39h265373d_0_kp
    - python_abi 3.9 3_cp39
    - readline 8.1.2 h2f4d8fa_1
    - setuptools 60.9.3 py39ha65689a_0
    - sqlite 3.37.0 h6632b73_0
    - tk 8.6.12 hd8af866_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h2f4d8fa_1
    - zlib 1.2.11 h4e544f5_1014
  run:
    - bx-python
    - libgcc-ng >=10.3.0
    - numpy
    - pysam =0.18.0
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
    - r-base
test:
  commands:
    - cpat.py -h
    - make_hexamer_tab.py -h
    - make_logitModel.py -h
about:
  home: https://cpat.readthedocs.io/en/latest/
  license: GNU General Public v2 or later (GPLv2+)
  license_file: LICENSE.txt
  summary: Coding Potential Assessment Tool
extra:
  copy_test_source_files: true
  final: true

