{% set version = "1.0" %}
package:
  name: k8
  version: {{ version }}

source:
  url: https://github.com/attractivechaos/k8/archive/refs/tags/v{{ version }}.tar.gz # [linux and aarch64]
  sha256: 1dbbe50de06f0ae71500d88ed3318d5a2884aeec0b43eda905f5cca5c01a5f72 # [linux and aarch64]
  url: https://github.com/attractivechaos/k8/releases/download/v{{ version }}/k8-{{ version }}.tar.bz2 # [linux]
  sha256: 61504dad2d63404bf523d3f8d0a8bfd72ec78aa7bd79bdf9291a4f629cfb9c02 # [linux]

build:
  number: 5
  run_exports:
    - {{ pin_subpackage("k8", max_pin="x.x.x") }}  

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - k8 -v | grep '^k8'

about:
  home: https://github.com/attractivechaos/k8
  license: MIT
  summary: "Lightweight JavaScript shell based on Google's V8 JavaScript engine"

extra:
  additional-platforms:
    - linux-aarch64
