# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /opt/recipe, last modified Tue Feb 22 19:56:24 2022
# ------------------------------------------------

package:
  name: kraken2
  version: 2.1.2
source:
  patches:
    - Makefile.patch
    - download_from_ftp.patch
  sha256: e5f431e8bc3d5493a79e1d8125f4aacbad24f9ea2cc9657b66da06a32bef6ff3
  url: https://github.com/DerrickWood/kraken2/archive/v2.1.2.tar.gz
build:
  number: '2'
  string: pl5321h9f5acd7_2_kp
requirements:
  build:
    #- _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-aarch64 2.36.1 h0d3074b_3
    - binutils_linux-aarch64 2.36 h7854541_10
    - gcc_impl_linux-aarch64 12.1.0 h9c21524_16
    - gcc_linux-aarch64 12.1.0 ha16010e_10
    - gxx_impl_linux-aarch64 12.1.0 h9c21524_16
    - gxx_linux-aarch64 12.1.0 hd2c83d7_10
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.36.1 h0ab8de2_3
    - libgcc-devel_linux-aarch64 12.1.0 hf2ffb8d_16
    - libgcc-ng 12.1.0 h3242a24_16
    - libgomp 12.1.0 h3242a24_16
    - libsanitizer 12.1.0 hd01590b_16
    - libstdcxx-devel_linux-aarch64 12.1.0 hf2ffb8d_16
    - libstdcxx-ng 12.1.0 hd01590b_16
    - make 4.3 h309ac5b_1
    - sysroot_linux-aarch64 2.17 h43d7e78_13
  host:
    #- _libgcc_mutex 0.1 main
    #- _openmp_mutex 4.5 2_gnu
    #- libgcc-ng 12.1.0 h3242a24_16
    #- libgomp 12.1.0 h3242a24_16
    #- libnsl 2.0.0 hf897c2e_0
    - libstdcxx-ng 12.1.0 hd01590b_16
    - perl 5.32.1 2_hf897c2e_perl5
  run:
    - _openmp_mutex * *_gnu
    - blast
    - libgcc-ng >=12.1.0
    - libstdcxx-ng >=12.1.0
    - perl >=5.32.1,<5.33.0a0 *_perl5
    - rsync
    - tar
    - wget
test:
  commands:
    - kraken2 --version
    - kraken2-build --version
    - kraken2-inspect --version
about:
  home: https://ccb.jhu.edu/software/kraken2/
  license: GPLv3
  license_file: LICENSE
  summary: Kraken2 is a system for assigning taxonomic labels to short DNA sequences,
    usually obtained through metagenomic studies.
extra:
  copy_test_source_files: true
  final: true
  identifiers:
    - biotools:kraken2
    - doi:10.1186/gb-2014-15-3-r46

