{% set name = "vg" %}
{% set version = "1.52.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://521github.com/vgteam/vg/releases/download/v{{ version }}/vg-arm64
  sha256: 66f507b0870a63644f6d745df70db92adc91faad08694e64d523988fa514362b
build:
  number: 0
  skip: true  # [osx]
  script:
    - mkdir -p ${PREFIX}/bin
    - mv vg-arm64 ${PREFIX}/bin/vg
    - chmod +x ${PREFIX}/bin/vg
  run_exports:
    - {{ pin_subpackage('vg', max_pin="x") }}
test:
  commands:
    - vg help

about:
  home: https://github.com/vgteam/vg
  license: MIT
  license_family: MIT
  summary: Variation graph data structures, interchange formats, alignment, genotyping, and variant calling methods

extra:
  skip-lints:
    - should_be_noarch_generic
