{% set version = "2.60.0" %}
{% set name = "Biobase" %}
{% set bioc = "3.17" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 7e427b98c2208f6c1c81cf4ec64caffc
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  run_exports:
    - '{{ pin_subpackage('bioconductor-biobase', max_pin="x.x") }}'
# Suggests: tools, tkWidgets, ALL, RUnit, golubEsets, BiocStyle, knitr
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.46.0,<0.47.0'
    - r-base >=3.6.3
    - libblas
    - liblapack
  run:
    - 'bioconductor-biocgenerics >=0.46.0,<0.47.0'
    - r-base >=3.6.3
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Biobase: Base functions for Bioconductor'
  description: 'Functions that are needed by many other packages or which replace R functions.'
extra:
  identifiers:
    - biotools:biobase
  additional-platforms:
    - linux-aarch64
