{% set version = "3.2.2" %}
{% set url = "https://github.com/refresh-bio/KMC/releases/download/v3.2.2/KMC3.2.2.linux.x64.tar.gz" %}  # [linux and x86_64]
{% set sha256 = "0b5574c3d59448aa4d93caaa967df9ea18407eb046742e4a9d00ac50179f46df" %}  # [linux and x86_64]
{% set url = "https://github.com/refresh-bio/KMC/releases/download/v3.2.2/KMC3.2.2.linux.arm64.tar.gz" %}  # [linux and aarch64]
{% set sha256 = "8e64916ff67d8e330eaca43161584569e0f1ebdf9254c37532b73916e2eb88bf" %}  # [linux and aarch64]
{% set url = "https://github.com/refresh-bio/KMC/releases/download/v3.2.2/KMC3.2.2.mac.x64.tar.gz" %}  # [osx]
{% set sha256 = "c39f1729170d8fe9480e3b6b227b2038b79e646039f6125b842fc827d36d9502" %}  # [osx]

package:
  name: kmc
  version: {{ version }}

source:
  url: {{ url }}
  sha256:  {{ sha256 }}

build:
  number: 4

requirements:
  run:
    - zlib
    - bzip2

test:
  commands:
    - kmc --help

about:
  home: https://github.com/refresh-bio/kmc
  summary: "Tools for efficient k-mer counting and filtering of reads based on k-mer content."
  description: |
    KMC is a utility designed for counting k-mers (sequences
    of consecutive k symbols) in a set of DNA sequences. KMC tools allow performing various operations on k-mers sets.
  license: GPL-3
  license_family: GPL
  license_file: gpl-3.0.txt
extra:
  additional-platforms:
    - linux-aarch64  
