package:
  name: "plink" 
  version: "1.90p"

build:
  number: 6

source:
  url: https://github.com/chrchang/plink-ng/archive/refs/tags/v2.00a5.10.tar.gz 
  sha256: 53d845c6a04f8fc701e6f58f6431654e36cbf6b79bff25099862d169a8199a45  
  patches: 
    - dynamic_zlib.patch

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - openblas
    - zlib
  host:
    - openblas
    - zlib      
  run:
    - openblas
    - zlib       
          

test:
  commands:
    - plink --help
    ###| grep "PLINK v1.90p"

about:
  home: https://www.cog-genomics.org/plink2
  license: GPL
  license_file: LICENSE
  summary: Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.
extra:
  additional-platforms:
    - linux-aarch64
