{% set version = "1.42.0" %}
{% set name = "GeneNetworkBuilder" %}
{% set bioc = "3.17" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 17f9146e215456d82474c6afd253cbcd
build:
  number: 0
  run_exports: # run_exports这个要配置上, 不然提交可能check不通过
    - {{ pin_subpackage('bioconductor-genenetworkbuilder', max_pin="x.x") }}
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: RUnit, BiocGenerics, RBGL, knitr, simpIntLists, shiny, STRINGdb, BiocStyle, magick, rmarkdown, org.Hs.eg.db
requirements:
  host:
    - 'bioconductor-graph >=1.78.0,<1.79.0'
    - 'bioconductor-rgraphviz >=2.44.0,<2.45.0'
    - r-base
    - r-htmlwidgets
    - r-plyr
    - 'r-rcpp >=0.9.13'
    - r-rjson
    - r-xml
    - libblas
    - liblapack
  run:
    - 'bioconductor-graph >=1.78.0,<1.79.0'
    - 'bioconductor-rgraphviz >=2.44.0,<2.45.0'
    - r-base
    - r-htmlwidgets
    - r-plyr
    - 'r-rcpp >=0.9.13'
    - r-rjson
    - r-xml
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'GeneNetworkBuilder: a bioconductor package for building regulatory network using ChIP-chip/ChIP-seq data and Gene Expression Data'
  description: 'Appliation for discovering direct or indirect targets of transcription factors using ChIP-chip or ChIP-seq, and microarray or RNA-seq gene expression data. Inputting a list of genes of potential targets of one TF from ChIP-chip or ChIP-seq, and the gene expression results, GeneNetworkBuilder generates a regulatory network of the TF.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra: # 一般我们要加这个extra配置,指示aarch64架构也支持,但是如果在build下已经指示是noarch了,就不要加这个了
  additional-platforms:
    - linux-aarch64

