package:
  name: lrzip
  version: "0.651"

source:
  url: http://ck.kolivas.org/apps/lrzip/lrzip-0.651.tar.xz
  md5: 375c25655828151635858b7759ff7306

build:
  number: 8
  run_exports:
    - {{ pin_subpackage('lrzip', max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - lzo
    - lz4
  run:
    - bzip2
    - zlib
    - lzo

test:
  commands:
    - lrzip --version

about:
  home: https://github.com/ckolivas/lrzip
  license: GPLv2
  summary: Long Range ZIP or Lzma RZIP.
           This is a compression program optimised for large files. The larger the file
           and the more memory you have, the better the compression advantage this will
           provide, especially once the files are larger than 100MB. The advantage can
           be chosen to be either size (much smaller than bzip2) or speed (much faster
           than bzip2).
extra:
  additional-platforms:
    - linux-aarch64

