package:
  name: 'bioconductor-data-packages'
  version: '20230718'
source:
build:
  number: 1
  noarch: generic
  run_exports:
    - {{ pin_subpackage("bioconductor-data-packages", max_pin=None) }}

requirements:
  run:
    - r-base >=3.6.3
    - curl
    - yq
test:
  commands:
    - yq --help
about:
  home: "https://github.com/bioconda/bioconda-utils"
  license: 'MIT'
  summary: 'A package to enable downloading and installation of Bioconductor data packages'
  additional-platforms:
    - linux-aarch64
