{% set version = "0.30.0" %}

package:
  name: csvtk
  version: {{ version }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('csvtk', max_pin='x.x') }}
  
source:
  - url: https://github.com/shenwei356/csvtk/releases/download/v{{ version }}/csvtk_darwin_amd64.tar.gz # [osx]
    md5: c415255e265ba0cd547806fdbda05652 # [osx]
  {% if target_platform == "linux-aarch64" %}
  url: https://github.com/shenwei356/csvtk/releases/download/v{{ version }}/csvtk_linux_arm64.tar.gz
  md5: 2a6dd840291d23971ff538eaf3de00ec
  {% elif target_platform == "linux-64" %}
  url: https://github.com/shenwei356/csvtk/releases/download/v{{ version }}/csvtk_linux_amd64.tar.gz
  md5: 8f5877d4fbea89609d64bd2679956476
  {% endif %}

test:
  commands:
    - csvtk version

about:
  home: https://github.com/shenwei356/csvtk
  summary: A cross-platform, efficient, practical CSV/TSV toolkit
  license: MIT

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
  additional-platforms:
    - linux-aarch64
